# Generated by Django 4.1.4 on 2023-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.CharField(max_length=30)),
                ('ac', models.IntegerField()),
                ('specialTL', models.IntegerField()),
                ('specialTD', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.CharField(max_length=30)),
                ('bonus', models.CharField(max_length=12)),
                ('nodes', models.IntegerField()),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrewQuarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewQuarters', models.CharField(max_length=10)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DefensiveCountermeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defensiveCountermeasures', models.CharField(max_length=15)),
                ('TLbonus', models.IntegerField()),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriftEngines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driftEngine', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('pcuRequirement', models.IntegerField()),
                ('maxSize', models.CharField(max_length=12)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpansionBays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansionBay', models.CharField(max_length=50)),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=12)),
                ('maneuverability', models.CharField(max_length=30)),
                ('hp', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('dt', models.IntegerField()),
                ('ct', models.IntegerField()),
                ('mounts', models.CharField(max_length=150)),
                ('expansionBays', models.IntegerField()),
                ('minimumCrew', models.IntegerField()),
                ('maximumCrew', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelWeaponsHeavy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=48)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelWeaponsLongarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=48)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=12)),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(max_length=60)),
                ('cost', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensors', models.CharField(max_length=36)),
                ('range', models.CharField(max_length=12)),
                ('modifier', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield', models.CharField(max_length=24)),
                ('totalSP', models.IntegerField()),
                ('regen', models.CharField(max_length=12)),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thrusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thruster', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=1)),
                ('speed', models.IntegerField()),
                ('piloting', models.IntegerField()),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('bpuLimiter', models.IntegerField()),
                ('special', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=48)),
                ('weaponClass', models.CharField(max_length=12)),
                ('weaponType', models.CharField(max_length=12)),
                ('speed', models.IntegerField()),
                ('range', models.CharField(max_length=12)),
                ('damage', models.CharField(max_length=12)),
                ('pcu', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('special', models.CharField(max_length=36)),
            ],
        ),
    ]